name: practice-workflow

on: 
   pull_request:            #Event
    types:                  #Activity types
      - opened
      - synchronize 
   workflow_dispatch:       # Event
   push:
    branches:
      - main                # main
      - 'dev-*'             # dev-main, dev-test
      - 'feat/**'           # feat/new, feat/new/dev
    paths-ignore:
      - '.github/workflows'
    paths:
      - 'rg-micro-dev'    

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install dependencies  
              run: |
                cd /home/runner/work/github-actions/github-actions/reactjs-app
                npm ci  
            - name: Run lint
              run: |
                cd /home/runner/work/github-actions/github-actions/practice-project/src 
                npm run lint 
            - name: Run test
              run: |
                  cd /home/runner/work/github-actions/github-actions/practice-project/src  
                  npm run test   
            - name: Run build
              run: |
                  cd /home/runner/work/github-actions/github-actions/practice-project/src
                  npm run build          
