name: reactjs-workflow

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install node JS
              uses: actions/setup-node@v3
              with:
                node-version: 18 
            # - name: Switch to working directory
            #   run: cd ./reactjs-app/
            # - name: pwd and ls
            #   run: |
            #     pwd
            #     cd /home/runner/work/github-actions/github-actions/reactjs-app
            #     ls
            - name: Install dependencies  
              run: |
                cd /home/runner/work/github-actions/github-actions/reactjs-app
                if [ -e yarn.lock ]; then
                yarn install --frozen-lockfile
                elif [ -e package-lock.json ]; then
                npm ci
                else
                npm i
                fi
            - name: Run tests
              run: npm test  

    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Get code
            uses: actions/checkout@v3
          - name: Install node JS
            uses: actions/setup-node@v3
            with:
              node-version: 18 
          - name: Switch to working directory
            run: cd ./reactjs-app    
          - name: Install dependenices
            run: |
                if [ -e yarn.lock ]; then
                yarn install --frozen-lockfile
                elif [ -e package-lock.json ]; then
                npm ci
                else
                npm i
                fi
          - name: Build project
            run: npm run build
          - name: Deploy
            run: echo "Deploying..."



              
